In [ ]:
# Nominal and Ordinal Categorical Features
# references
# Albon, Machine Learning Cookbook
# March 2022

In [ ]:
import sys
#clear all variables (from last session)
sys.modules[__name__].__dict__.clear()
import os, sys, time, random, itertools, shutil
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [ ]:
# Import libraries
import numpy 
from sklearn.preprocessing import LabelBinarizer, MultiLabelBinarizer

In [ ]:
# Create feature
feature = numpy.array([["Apples"],["Pears"],["Cherries"],["Grapes"],["Oranges"], ["Pineaple"], ["Jackfruit"]])
playdate2 = numpy.array([['No'],['No'],['Yes'],['Yes'],['Yes'],['No'],['Yes'],['No'],['Yes'],['Yes'],['Yes'],['Yes'],['Yes'],['No']])

In [ ]:
# Create one-hot encoder
one_hot = LabelBinarizer()
one_hot2 = LabelBinarizer()

# One-hot encode feature
one_hot_feature = one_hot.fit_transform(feature)
one_hot_feature2 = one_hot.fit_transform(playdate2)
print(one_hot_feature)
print(one_hot_feature2)

[[1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]]
[[0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [ ]:
# Get the classes again
print(one_hot.classes_)

['Apples' 'Cherries' 'Grapes' 'Jackfruit' 'Oranges' 'Pears' 'Pineaple']


In [ ]:
# What about multiple  classes?
multiclass_feature = [("Apples", "Oranges"),("Cherries", "Apples"),("Oranges", "Grapes"),("Grapes", "Apples"),("Apples", "Pears")]

In [ ]:
# Create multiclass one-hot encoder
one_hot_multiclass = MultiLabelBinarizer()

# One-hot encode multiclass feature
one_hot_multiclass_features = one_hot_multiclass.fit_transform(multiclass_feature)
print(one_hot_multiclass_features)

[[1 0 0 1 0]
 [1 1 0 0 0]
 [0 0 1 1 0]
 [1 0 1 0 0]
 [1 0 0 0 1]]


In [ ]:
# Get the labels again
print(one_hot_multiclass.classes_)

['Apples' 'Cherries' 'Grapes' 'Oranges' 'Pears']


In [ ]:
# Ordinal Categorical Features

weather = ['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
playdate = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']


In [ ]:
import pandas
df_weather = pandas.DataFrame({"weather_data":weather})
df_temp = pandas.DataFrame({"temp_data":temp})
df_playdate = pandas.DataFrame({"playdate_data":playdate})

In [ ]:
weather_scale_mapper = {"Sunny":2, "Rainy":1, "Overcast":0}
temp_scale_mapper = {"Hot":2, "Cool":1, "Mild":0}
playdate_scale_mapper = {"Yes":1, "No":0}

In [ ]:
df_weather["weather_data"].replace(weather_scale_mapper)
df_temp["temp_data"].replace(temp_scale_mapper)
df_playdate["playdate_data"].replace(playdate_scale_mapper)

print(df_weather["weather_data"])
print(df_weather["weather_data"].replace(weather_scale_mapper))

0        Sunny
1        Sunny
2     Overcast
3        Rainy
4        Rainy
5        Rainy
6     Overcast
7        Sunny
8        Sunny
9        Rainy
10       Sunny
11    Overcast
12    Overcast
13       Rainy
Name: weather_data, dtype: object
0     2
1     2
2     0
3     1
4     1
5     1
6     0
7     2
8     2
9     1
10    2
11    0
12    0
13    1
Name: weather_data, dtype: int64
